CORE
main.py

^\s*Throwing an exception of type TypeError but there is not catch for it.$
