THOROUGH
main.py
--force-malloc-success --unwind 9 --ir
^VERIFICATION FAILED$
